### ISSUE TITLE
Suggestion: make it a real game

### ISSUE THREAD

**Issue by PierreTurnbull** [tversteeg/castle-game#4]
At the moment, castle-game is more of a simulation than an actual game. Few things could make it become a real game that would be fun to play:
- make an enemy unit generation to have more than just 1 wave of enemies coming from the other side
- make a gold/credit system to buy units
- make a HP system for the base or a zone to reach in order to win
- make few more units, eg: cavalry (fast, can charge through units), mage (expensive and weak but can buff surrounding alliees and cast powerful spells), catapults (expensive, weak and don't move, units can pass through it. high damage, high reload time).

**Comment by PierreTurnbull** [comment]
My bad, I just saw the TODO List. Have fun! :)

**Comment by tversteeg** [comment]
Yes it's still in a very early stage of development, I'm still figuring out a lot of the basic stuff like animation etc.
I do like your suggestions, I'm not sure about the mage because it implies that the game will have a high-fantasy setting/theme. I do like that but I want to keep it open, maybe a more "realistic" medieval setting fits better..

**Comment by PierreTurnbull** [comment]
I will be happy to discover later versions!

About accessibility, shouldn't it be better, if possible, to download a simple executable file (with libraries if needed), without having to download Rust and compile the project?

**Comment by tversteeg** [comment]
That's why there's the [release](https://github.com/tversteeg/castle-game/releases) tab :)
